In [1]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

device = "cuda" if torch.cuda.is_available() else "cpu"

# Check for GPU (should return True)
print(torch.cuda.is_available())

True


In [2]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [3]:
tensor_gpu = tensor.to(device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [4]:
tensor_gpu = tensor_gpu.to("cpu").numpy()
print(tensor_gpu)

[1 2 3]
